// <auto-generated />
using System;
using GridlineInterviewAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridlineInterviewAPI.DAL.Migrations
{
    [DbContext(typeof(GridlineContext))]
    [Migration("20230621080546_audit")]
    partial class audit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("DriverTruck", b =>
                {
                    b.Property<int>("DriversId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrucksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DriversId", "TrucksId");

                    b.HasIndex("TrucksId");

                    b.ToTable("DriverTruck");
                });

            modelBuilder.Entity("GridlineInterviewAPI.Core.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Audit_Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Audit_Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("GridlineInterviewAPI.Core.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Audit_Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Audit_Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("DriverTruck", b =>
                {
                    b.HasOne("GridlineInterviewAPI.Core.Models.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridlineInterviewAPI.Core.Models.Truck", null)
                        .WithMany()
                        .HasForeignKey("TrucksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
